### Variáveis
@URL_API = http://localhost:3000

### GET na raiz da API
GET {{URL_API}}

### POST no produtos
POST {{URL_API}}/produtos
Content-Type: application/json

{
    "nome": "Farinha",
    "preco": 10.8
}

### GET nos produtos
GET {{URL_API}}/produtos

### GET no produto de id 100
GET {{URL_API}}/produtos/6912ad3a9935acd00bdba1b0

### GET no produto de id 100
GET {{URL_API}}/produtos/nome/Arroz

### PATCH no produtos
PATCH http://localhost:3000/produtos/6912ad3a9935acd00bdba1b0
Content-Type: application/json

{
  "nome": "Arroz Atualizado",
  "preco": 20
}

### DELETE no produto de id 100
DELETE http://localhost:3000/produtos/69d2d59f7336715c7a447663